name: deploy-app

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-app.yml
      - app/**

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./app

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup node env 🏗
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: "npm"
          cache-dependency-path: "./app/package-lock.json"

      - name: Install dependencies 👨🏻‍💻
        run: npm ci

      - name: Run linter 👀
        run: npm run lint

      - name: Run tests 🧪
        run: npm run test:unit -- --run

      - name: Run build 👷🏻
        run: npm run build

      - name: 🚀 Ship the whole thin
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        with:
          flags: "-auvzrl --delete"
          options: ""
          ssh_options: ""
          src: "./app/dist/*"
          dest: ${{vars.DEPLOY_DEST}}/app
